services:
  - type: web
    name: mochi-bakehouse
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.17.1
      - key: MONGODB_DB
        value: mochi_bakehouse
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
